name: Python check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
    steps:
        - uses: actions/checkout@v4
        - name: Install uv
          uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"
        - name: Install dependencies
          run: uv sync --all-extras --dev
        - name: Lint with ruff
          run: uv run ruff check .
        - name: Check formatting with black
          run: uv run black . --check --verbose
        - name: Run Pytest tests
          run: |
            uv add -r src/requirements.txt
            uv run pytest
